server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/metodists_rf_task_tracker
    username: postgres
    password: roottoor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update